#!/bin/bash
# Append Jira ticket ID to commit messages

FILE=$1
MESSAGE=$(cat $FILE)
SUBJECT=$(echo "$MESSAGE" | head -1)

# Don't make modifications to a squash/fixup commit
if [[ $SUBJECT =~ ^squash!|^fixup! ]];then
  exit 0;
fi

# Pendo standard branch names take the form:
# initials-app-12345-auto-fe-dev
# we don't care about initials or anything after the number.
TICKET=$(git rev-parse --abbrev-ref HEAD | grep -Eo '(\w+-)?[0-9]+' | tr "[:lower:]" "[:upper:]")

# Don't append empty ticket numbers to the commit subject
if [[ $TICKET == "" || "$SUBJECT" == *"$TICKET" ]];then
  exit 0;
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "1s/$/ $TICKET/" $FILE
else
    sed -i "1s/$/ $TICKET/" $FILE
fi
